# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/delete-me',
                'doc_host': 'https://jbwhit.github.io',
                'git_url': 'https://github.com/jbwhit/delete-me',
                'lib_path': 'delete_me'},
  'syms': {'delete_me.core': {'delete_me.core.foo': ('core.html#foo', 'delete_me/core.py')}}}
